#! /bin/sh

isUpstart() {
    /sbin/init --version 2>/dev/null | grep -q 'upstart'
    #echo "result=$?"
    if [ "$?" = "0" ]; then
        return 0
    else 
        return 1
    fi
}

isSystemd() {
    /bin/systemctl 2>/dev/null | grep -q '\-\.mount'
    #echo "result=$?"
    if [ "$?" = "0" ]; then
        return 0
    else 
        return 1
    fi
}

if [ "$1" = "remove" ]; then

    if [ -e /etc/logrotate.d/stream-schedule-liquidsoap ]; then
        rm /etc/logrotate.d/stream-schedule-liquidsoap
    fi

    if [ -e /etc/init/stream-schedule-liquidsoap.conf ]; then
        rm /etc/init/stream-schedule-liquidsoap.conf
    fi

    if [ -e /var/run/stream-schedule/stream-schedule-liquidsoap.pid ]; then
        rm /var/run/stream-schedule/stream-schedule-liquidsoap.pid
    fi

    if [ -e /var/log/upstart/stream-schedule-liquidsoap.log ]; then
        rm -r /var/log/upstart/stream-schedule-liquidsoap*
    fi

    if [ -e /var/log/stream-schedule/stream-schedule-liquidsoap.log ]; then
        rm -r /var/log/stream-schedule/stream-schedule-liquidsoap*
    fi
fi

if [ "$1" = "purge" ]; then
    if [ -e /etc/stream-schedule/liquidsoap/ ]; then
        rm -r /etc/stream-schedule/liquidsoap/
    fi
fi

if isSystemd; then
	echo "reload systemd services"
	systemctl daemon-reload
fi

exit 0;

#DEBHELPER#
